# Generated by Django 4.0.5 on 2022-07-09 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=500)),
                ('image', models.URLField(blank=True)),
                ('listing_start_price', models.FloatField()),
                ('current_price', models.FloatField()),
                ('current_bidder', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_highest_bidder', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
                ('watchers', models.ManyToManyField(blank=True, related_name='current_watchers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
