# Generated by Django 4.0.5 on 2022-07-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='current_price',
        ),
    ]
