# Generated by Django 4.0.5 on 2022-07-12 16:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('', 'No Choices Listed'), ('SPORTS', 'Sport'), ('FASHION', 'Fashion'), ('ELECTRONICS', 'Electronics')], max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='listings',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.ManyToManyField(default='', related_name='item_category', to='auctions.category'),
        ),
    ]
