# Generated by Django 4.0.5 on 2022-07-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_category_alter_listings_watchers_listings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='item_category', to='auctions.category'),
        ),
    ]
