# Generated by Django 4.0.5 on 2022-07-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listings_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='current_price',
        ),
    ]
