# Generated by Django 4.0.5 on 2022-07-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_listings_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='current_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listings',
            name='listing_start_price',
            field=models.IntegerField(),
        ),
    ]
