# Generated by Django 4.0.5 on 2022-07-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_listings_current_price_alter_bids_bid_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listings',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listings',
            name='listing_start_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
