# Generated by Django 4.0.5 on 2022-07-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_bids_bid_price_alter_listings_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
